name: "Download base artifact"
description: "Download the base artifact for the current workflow"
author: andrewiggins
branding:
  icon: download
  color: yellow
inputs:
  artifact:
    description: "The name of the artifact to download"
    required: true
  workflow:
    description: "The workflow file name that generates the desired artifact. Defaults to the current workflow."
    required: false
  path:
    description: "The path to download the artifact to. Defaults to the current working directory."
    required: false
  required:
    description: "If required, this action will fail if a matching artifact cannot be found"
    required: false
  baseRef:
    description: "The git ref whose artifact is to be downloaded. For branches prefix branch name with 'heads/'. For tags prefix tag with 'tags/'. Also accepts commit shas. Automatically determined for pull requests and push events."
    required: false
  github_token:
    description: "The GITHUB_TOKEN for the current workflow run"
    required: false
    default: ${{github.token}}
runs:
  using: "node20"
  main: "dist/action.js"
