name: "Download base artifact"
description: "Download the base artifact for the current workflow"
author: andrewiggins
branding:
  icon: download
  color: yellow
inputs:
  github_token:
    description: "The GITHUB_TOKEN for the current workflow run"
    required: false
    default: ${{github.token}}
  workflow:
    description: "The workflow file name that generates the desired artifact. Defaults to the current workflow."
    required: false
  artifact:
    description: "The name of the artifact to download"
    required: true
  path:
    description: "The path to download the artifact to. Defaults to the current working directory."
    required: false
  required:
    description: "If required, this action will fail if a matching artifact cannot be found"
    required: false
  baseRef:
    description: "The git ref that contains the base commit whose artifact is to be downloaded"
    required: false
  baseSha:
    description: "The git commit SHA whose artifact for the given workflow should be downloaded"
    required: false
runs:
  using: "node16"
  main: "dist/action.js"
